### ISSUE TITLE
scriblib/autobib citations should link to bib entry.

### ISSUE THREAD

**Issue by LeifAndersen** [racket/scribble#124]
When using bibtex+hyperref, clicking on a paper reference links to its location in the bibliography. We should do the same thing with scriblib/autobib.

**Comment by bennn** [comment]
`@zeeshanlakhani` on Slack found a similar issue:
- "citations" in `scribble/acmart @acmsmall` jump to the first page (bad)
- "citations" in `scribble/acmart @sigplan` jump to the bibliography (good)

I have "citations" in quotes because I mean "the link generated by calling a function generated by calling `define-cite`".

Example document attached. Unzip, then run `make pdf` to build a document.
Clicking the `[1]` on the first page brings me to the top of the first page.

[test.tar.gz](https://github.com/racket/scribble/files/1306645/test.tar.gz)

**Comment by bennn** [comment]
Fixed by #145
